# Okay so currently coder runs locally and I access it via an IP. Thus I cannot use the github to access
# my coder as it requires an url to execute terraform plan and upload the templates to coder. This is definetly possible tho.
# 

name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

#      - name: Set up Coder CLI
#        uses: coder/setup-action@v1
#        with:
#          access_url: "https://coder.example.com"
#          coder_session_token: ${{ secrets.cicd }}

#      - name: Terraform Format
#        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

#      - name: Terraform Plan
#        run: terraform plan
